INSERT INTO car (id, year, brand, color, model) values (1, 2006, 'HONDA', 'Orange', 'E-350 Super Duty Van');
INSERT INTO car (id, year, brand, color, model) values (2, 2007, 'HONDA', 'Red', 'Savana 1500');
INSERT INTO car (id, year, brand, color, model) values (3, 2004, 'VOLVO', 'Aquamarine', 'Montana');
INSERT INTO car (id, year, brand, color, model) values (4, 2010, 'VOLVO', 'Crimson', 'CTS-V');
INSERT INTO car (id, year, brand, color, model) values (5, 1992, 'JAGUAR', 'Maroon', 'Grand Marquis');
INSERT INTO car (id, year, brand, color, model) values (6, 1991, 'RENAULT', 'Orange', 'Fox');
INSERT INTO car (id, year, brand, color, model) values (7, 2006, 'RENAULT', 'Goldenrod', 'Sienna');
INSERT INTO car (id, year, brand, color, model) values (8, 1993, 'AUDI', 'Crimson', 'Eclipse');
INSERT INTO car (id, year, brand, color, model) values (9, 2004, 'VOLVO', 'Mauv', 'Swift');
INSERT INTO car (id, year, brand, color, model) values (10, 2011, 'RENAULT', 'Indigo', '4Runner');
INSERT INTO car (id, year, brand, color, model) values (11, 1996, 'JAGUAR', 'Goldenrod', 'Mystique');
INSERT INTO car (id, year, brand, color, model) values (12, 2003, 'HONDA', 'Aquamarine', 'E350');
INSERT INTO car (id, year, brand, color, model) values (13, 2009, 'BMW', 'Mauv', '1 Series');
INSERT INTO car (id, year, brand, color, model) values (14, 2008, 'HONDA', 'Indigo', 'E350');
INSERT INTO car (id, year, brand, color, model) values (15, 1993, 'VOLVO', 'Red', 'Concorde');
INSERT INTO car (id, year, brand, color, model) values (16, 1995, 'MERCEDES', 'Khaki', 'Neon');
INSERT INTO car (id, year, brand, color, model) values (17, 1994, 'HONDA', 'Fuscia', 'Civic');
INSERT INTO car (id, year, brand, color, model) values (18, 1995, 'HONDA', 'Red', 'Taurus');
INSERT INTO car (id, year, brand, color, model) values (19, 2003, 'VOLVO', 'Goldenrod', 'XC70');
INSERT INTO car (id, year, brand, color, model) values (20, 1993, 'HONDA', 'Orange', 'Econoline E350');
INSERT INTO car (id, year, brand, color, model) values (21, 2000, 'VOLVO', 'Crimson', 'Century');
INSERT INTO car (id, year, brand, color, model) values (22, 1986, 'RENAULT', 'Fuscia', 'Cabriolet');
INSERT INTO car (id, year, brand, color, model) values (23, 2000, 'VOLVO', 'Blue', '300M');
INSERT INTO car (id, year, brand, color, model) values (24, 2003, 'BMW', 'Turquoise', '911');
INSERT INTO car (id, year, brand, color, model) values (25, 1998, 'BMW', 'Crimson', 'QX');
INSERT INTO car (id, year, brand, color, model) values (26, 2010, 'RENAULT', 'Khaki', 'Camry Hybrid');
INSERT INTO car (id, year, brand, color, model) values (27, 1990, 'VOLVO', 'Aquamarine', 'Electra');
INSERT INTO car (id, year, brand, color, model) values (28, 2012, 'BMW', 'Teal', 'Panamera');
INSERT INTO car (id, year, brand, color, model) values (29, 1995, 'HONDA', 'Goldenrod', 'F250');
INSERT INTO car (id, year, brand, color, model) values (30, 1986, 'VOLVO', 'Violet', 'SJ 410');
INSERT INTO car (id, year, brand, color, model) values (31, 2003, 'RENAULT', 'Aquamarine', 'Celica');
INSERT INTO car (id, year, brand, color, model) values (32, 2007, 'BMW', 'Green', '350Z');
INSERT INTO car (id, year, brand, color, model) values (33, 1985, 'VOLVO', 'Yellow', 'W201');
INSERT INTO car (id, year, brand, color, model) values (34, 2002, 'VOLVO', 'Purple', 'Impala');
INSERT INTO car (id, year, brand, color, model) values (35, 2009, 'HONDA', 'Crimson', 'HONDAspeed 3');
INSERT INTO car (id, year, brand, color, model) values (36, 2002, 'HONDA', 'Violet', 'TL');
INSERT INTO car (id, year, brand, color, model) values (37, 2003, 'AUDI', 'Violet', 'Allroad');
INSERT INTO car (id, year, brand, color, model) values (38, 2009, 'HONDA', 'Yellow', 'Expedition');
INSERT INTO car (id, year, brand, color, model) values (39, 2009, 'AUDI', 'Indigo', 'H3');
INSERT INTO car (id, year, brand, color, model) values (40, 2007, 'VOLVO', 'Turquoise', 'Arnage');
INSERT INTO car (id, year, brand, color, model) values (41, 1999, 'HONDA', 'Khaki', '1500 Club Coupe');
INSERT INTO car (id, year, brand, color, model) values (42, 1993, 'VOLVO', 'Orange', 'Acclaim');
INSERT INTO car (id, year, brand, color, model) values (43, 1993, 'VOLVO', 'Violet', '300SL');
INSERT INTO car (id, year, brand, color, model) values (44, 1986, 'VOLVO', 'Crimson', 'Somerset');
INSERT INTO car (id, year, brand, color, model) values (45, 2008, 'VOLVO', 'Puce', 'LaCrosse');
INSERT INTO car (id, year, brand, color, model) values (46, 1993, 'VOLVO', 'Crimson', 'Colt');
INSERT INTO car (id, year, brand, color, model) values (47, 2012, 'VOLVO', 'Khaki', 'Veracruz');
INSERT INTO car (id, year, brand, color, model) values (48, 2007, 'JAGUAR', 'Fuscia', 'Sorento');
INSERT INTO car (id, year, brand, color, model) values (49, 1997, 'VOLVO', 'Pink', 'Neon');
INSERT INTO car (id, year, brand, color, model) values (50, 1998, 'HONDA', 'Yellow', 'Savana 2500');
INSERT INTO car (id, year, brand, color, model) values (51, 2003, 'VOLVO', 'Goldenrod', 'Seville');
INSERT INTO car (id, year, brand, color, model) values (52, 1993, 'HONDA', 'Khaki', 'Integra');
INSERT INTO car (id, year, brand, color, model) values (53, 2011, 'JAGUAR', 'Fuscia', 'Phantom');
INSERT INTO car (id, year, brand, color, model) values (54, 2004, 'HONDA', 'Red', 'Canyon');
INSERT INTO car (id, year, brand, color, model) values (55, 1990, 'JAGUAR', 'Goldenrod', 'Loyale');
INSERT INTO car (id, year, brand, color, model) values (56, 2005, 'VOLVO', 'Blue', 'Rainier');
INSERT INTO car (id, year, brand, color, model) values (57, 2008, 'HONDA', 'Maroon', 'Edge');
INSERT INTO car (id, year, brand, color, model) values (58, 2012, 'BMW', 'Khaki', 'Xterra');
INSERT INTO car (id, year, brand, color, model) values (59, 1998, 'RENAULT', 'Mauv', 'Camry');
INSERT INTO car (id, year, brand, color, model) values (60, 1997, 'MERCEDES', 'Mauv', 'Ram Van 3500');
INSERT INTO car (id, year, brand, color, model) values (61, 1992, 'HONDA', 'Fuscia', 'Probe');
INSERT INTO car (id, year, brand, color, model) values (62, 1986, 'VOLVO', 'Purple', 'Firefly');
INSERT INTO car (id, year, brand, color, model) values (63, 1994, 'RENAULT', 'Khaki', 'Golf');
INSERT INTO car (id, year, brand, color, model) values (64, 1998, 'HONDA', 'Violet', '2500');
INSERT INTO car (id, year, brand, color, model) values (65, 2004, 'HONDA', 'Puce', 'Tribute');
INSERT INTO car (id, year, brand, color, model) values (66, 1998, 'JAGUAR', 'Purple', 'SC');
INSERT INTO car (id, year, brand, color, model) values (67, 1996, 'MERCEDES', 'Violet', 'Dakota Club');
INSERT INTO car (id, year, brand, color, model) values (68, 2003, 'JAGUAR', 'Violet', 'RX');
INSERT INTO car (id, year, brand, color, model) values (69, 2007, 'BMW', 'Turquoise', 'Versa');
INSERT INTO car (id, year, brand, color, model) values (70, 2000, 'HONDA', 'Orange', 'Yukon XL 1500');
INSERT INTO car (id, year, brand, color, model) values (71, 2001, 'HONDA', 'Purple', 'B2500');
INSERT INTO car (id, year, brand, color, model) values (72, 2000, 'RENAULT', 'Mauv', 'Sienna');
INSERT INTO car (id, year, brand, color, model) values (73, 2009, 'JAGUAR', 'Violet', 'SC');
INSERT INTO car (id, year, brand, color, model) values (74, 1997, 'HONDA', 'Puce', 'B-Series Plus');
INSERT INTO car (id, year, brand, color, model) values (75, 2007, 'JAGUAR', 'Khaki', 'Hemisfear');
INSERT INTO car (id, year, brand, color, model) values (76, 1959, 'BMW', 'Pink', '600');
INSERT INTO car (id, year, brand, color, model) values (77, 1989, 'VOLVO', 'Aquamarine', 'LeSabre');
INSERT INTO car (id, year, brand, color, model) values (78, 2008, 'VOLVO', 'Maroon', 'Equinox');
INSERT INTO car (id, year, brand, color, model) values (79, 2012, 'RENAULT', 'Goldenrod', 'TundraMax');
INSERT INTO car (id, year, brand, color, model) values (80, 2002, 'JAGUAR', 'Violet', 'Esprit');
INSERT INTO car (id, year, brand, color, model) values (81, 1996, 'MERCEDES', 'Mauv', 'Dakota');
INSERT INTO car (id, year, brand, color, model) values (82, 2006, 'HONDA', 'Pink', 'F150');
INSERT INTO car (id, year, brand, color, model) values (83, 2001, 'JAGUAR', 'Goldenrod', 'Sephia');
INSERT INTO car (id, year, brand, color, model) values (84, 1998, 'HONDA', 'Turquoise', 'Odyssey');
INSERT INTO car (id, year, brand, color, model) values (85, 1994, 'JAGUAR', 'Violet', 'Continental');
INSERT INTO car (id, year, brand, color, model) values (86, 2001, 'HONDA', 'Puce', 'Explorer Sport');
INSERT INTO car (id, year, brand, color, model) values (87, 2000, 'VOLVO', 'Maroon', 'Montana');
INSERT INTO car (id, year, brand, color, model) values (88, 2004, 'VOLVO', 'Teal', 'Express 3500');
INSERT INTO car (id, year, brand, color, model) values (89, 2004, 'BMW', 'Goldenrod', '645');
INSERT INTO car (id, year, brand, color, model) values (90, 2007, 'HONDA', 'Red', 'Savana');
INSERT INTO car (id, year, brand, color, model) values (91, 2000, 'AUDI', 'Blue', 'A4');
INSERT INTO car (id, year, brand, color, model) values (92, 1994, 'MERCEDES', 'Blue', 'Viper');
INSERT INTO car (id, year, brand, color, model) values (93, 2011, 'JAGUAR', 'Yellow', 'RX Hybrid');
INSERT INTO car (id, year, brand, color, model) values (94, 2000, 'VOLVO', 'Indigo', 'Suburban 2500');
INSERT INTO car (id, year, brand, color, model) values (95, 1996, 'HONDA', 'Blue', '1500 Club Coupe');
INSERT INTO car (id, year, brand, color, model) values (96, 2008, 'JAGUAR', 'Pink', '57');
INSERT INTO car (id, year, brand, color, model) values (97, 2007, 'JAGUAR', 'Yellow', 'Outback');
INSERT INTO car (id, year, brand, color, model) values (98, 2005, 'VOLVO', 'Aquamarine', 'Equinox');
INSERT INTO car (id, year, brand, color, model) values (99, 1993, 'JAGUAR', 'Teal', 'Town Car');
INSERT INTO car (id, year, brand, color, model) values (100, 2000, 'VOLVO', 'Mauv', 'C70');
